ERROR - 2025-08-24 03:13:59 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 03:13:59 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:13:59 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:13:59\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:13:59\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:13:59 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:13:59\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:13:59\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:13:59\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 03:14:04 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 03:14:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:04\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:04\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:04 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 03:14:09 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 03:14:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:09 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:09 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 03:14:09 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 03:14:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:09 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:09 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 03:14:10 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 03:14:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:10 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:10\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:10\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:10 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:10\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:10\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:10\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 04:01:34 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 04:01:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:01:34 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:34\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:34\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:01:34 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:34\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:34\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:34\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 04:01:42 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 04:01:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:01:42 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:42\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:42\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:01:42 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:42\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:42\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:42\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 04:02:18 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 04:02:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:02:18 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:02:18\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:02:18\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:02:18 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:02:18\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:02:18\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:02:18\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 04:05:28 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 04:05:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:05:28 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:05:28\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:05:28\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:05:28 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:05:28\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:05:28\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:05:28\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 07:37:47 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 07:37:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 07:37:48 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'yuyuyu\', 0, \'2025-08-24 07:37:47\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'yuyuyu\', 0, \'2025-08-24 07:37:47\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 07:37:48 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'yuyuyu\', 0, \'2025-08-24 07:37:47\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'yuyuyu\', 0, \'2025-08-24 07:37:47\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'yuyuyu\', 0, \'2025-08-24 07:37:47\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:17:47 --> ErrorException: Class App\Database\Migrations\CreateBooks contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (CodeIgniter\Database\Migration::down)
[Method: CLI, Route: migrate]
in APPPATH\Database\Migrations\2025-08-23-184439_CreateBooks.php on line 7.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-08-24 08:18:00 --> ErrorException: Class App\Database\Migrations\CreateBooks contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (CodeIgniter\Database\Migration::down)
[Method: CLI, Route: migrate]
in APPPATH\Database\Migrations\2025-08-23-184439_CreateBooks.php on line 7.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2025-08-24 08:21:33 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:21:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:21:33 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:21:33\', \'2025-08-24 08:21:33\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:21:33\', \'2025-08-24 08:21:33\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:21:33 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:21:33\', \'2025-08-24 08:21:33\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:21:33\', \'2025-08-24 08:21:33\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:21:33\', \'2025-08-24 08:21:33\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 08:23:37 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:23:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:23:37 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:37\', \'2025-08-24 08:23:37\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:37\', \'2025-08-24 08:23:37\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:23:37 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:37\', \'2025-08-24 08:23:37\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:37\', \'2025-08-24 08:23:37\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:37\', \'2025-08-24 08:23:37\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 08:23:47 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:23:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:23:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:46\', \'2025-08-24 08:23:46\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:46\', \'2025-08-24 08:23:46\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:23:47 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:46\', \'2025-08-24 08:23:46\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:46\', \'2025-08-24 08:23:46\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:46\', \'2025-08-24 08:23:46\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 08:29:54 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:29:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:29:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:29:54\', \'2025-08-24 08:29:54\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:29:54\', \'2025-08-24 08:29:54\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:29:54 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:29:54\', \'2025-08-24 08:29:54\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:29:54\', \'2025-08-24 08:29:54\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:29:54\', \'2025-08-24 08:29:54\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 08:30:03 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:30:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:30:03 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:03\', \'2025-08-24 08:30:03\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:03\', \'2025-08-24 08:30:03\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:30:03 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:03\', \'2025-08-24 08:30:03\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:03\', \'2025-08-24 08:30:03\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:03\', \'2025-08-24 08:30:03\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 08:30:14 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:30:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:30:14 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:14\', \'2025-08-24 08:30:14\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:14\', \'2025-08-24 08:30:14\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:30:14 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:14\', \'2025-08-24 08:30:14\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:14\', \'2025-08-24 08:30:14\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:14\', \'2025-08-24 08:30:14\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 08:30:48 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:30:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:30:48 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:48\', \'2025-08-24 08:30:48\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:48\', \'2025-08-24 08:30:48\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:30:48 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:48\', \'2025-08-24 08:30:48\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:48\', \'2025-08-24 08:30:48\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:48\', \'2025-08-24 08:30:48\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 08:32:34 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:32:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:32:34 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:32:34\', \'2025-08-24 08:32:34\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:32:34\', \'2025-08-24 08:32:34\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:32:34 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:32:34\', \'2025-08-24 08:32:34\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:32:34\', \'2025-08-24 08:32:34\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:32:34\', \'2025-08-24 08:32:34\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 12:33:38 --> ErrorException: Undefined array key "title"
[Method: GET, Route: admin/books]
in APPPATH\Views\admin\books.php on line 11.
 1 APPPATH\Views\admin\books.php(11): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "title"', 'C:\\xampp\\htdocs\\codeigniter4order\\app\\Views\\admin\\books.php', 11)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\codeigniter4order\\app\\Views\\admin\\books.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('admin/books', [], true)
 5 APPPATH\Controllers\Admin\Books.php(15): view('admin/books', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Books->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Books))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 16:38:41 --> ErrorException: Undefined array key "title"
[Method: GET, Route: admin/books]
in APPPATH\Views\admin\books.php on line 11.
 1 APPPATH\Views\admin\books.php(11): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "title"', 'C:\\xampp\\htdocs\\codeigniter4order\\app\\Views\\admin\\books.php', 11)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\codeigniter4order\\app\\Views\\admin\\books.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('admin/books', [], true)
 5 APPPATH\Controllers\Admin\Books.php(15): view('admin/books', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Books->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Books))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 17:44:56 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-08-24 17:44:56 --> 220 smtp.gmail.com ESMTP d9443c01a7336-2466886456csm47105905ad.72 - gsmtp

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

starttls: 220 2.0.0 Ready to start TLS

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-2466886456csm47105905ad.72 - gsmtp

CRITICAL - 2025-08-24 17:44:56 --> TypeError: implode(): Argument #2 ($array) must be of type ?array, string given
[Method: POST, Route: order/submit]
in APPPATH\Controllers\ShopController.php on line 110.
 1 APPPATH\Controllers\ShopController.php(110): implode(', ', '220 smtp.gmail.com ESMTP d9443c01a7336-2466886456csm47105905ad.72 - gsmtp
<br><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre><pre>starttls: 220 2.0.0 Ready to start TLS
</pre><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre>Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-2466886456csm47105905ad.72 - gsmtp
<br>Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br><pre>Date: Sun, 24 Aug 2025 17:44:51 +0000
From: &quot;Your Shop Name&quot; &lt;johir@pixelbuildbd.com&gt;
Return-Path: &lt;johir@pixelbuildbd.com&gt;
To: johirulislam6442@gmail.com
Subject: =?UTF-8?Q?New=20Order=20Received?=
Reply-To: &lt;johir@pixelbuildbd.com&gt;
User-Agent: CodeIgniter
X-Sender: johir@pixelbuildbd.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;68ab4f9366e6e6.95072221@pixelbuildbd.com&gt;
Mime-Version: 1.0

</pre>')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 17:47:56 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-08-24 17:47:56 --> 220 smtp.gmail.com ESMTP 98e67ed59e1d1-3254af5f9c7sm4861335a91.23 - gsmtp

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

starttls: 220 2.0.0 Ready to start TLS

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 98e67ed59e1d1-3254af5f9c7sm4861335a91.23 - gsmtp

CRITICAL - 2025-08-24 17:47:56 --> TypeError: implode(): Argument #2 ($array) must be of type ?array, string given
[Method: POST, Route: order/submit]
in APPPATH\Controllers\ShopController.php on line 110.
 1 APPPATH\Controllers\ShopController.php(110): implode(', ', '220 smtp.gmail.com ESMTP 98e67ed59e1d1-3254af5f9c7sm4861335a91.23 - gsmtp
<br><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre><pre>starttls: 220 2.0.0 Ready to start TLS
</pre><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre>Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 98e67ed59e1d1-3254af5f9c7sm4861335a91.23 - gsmtp
<br>Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br><pre>Date: Sun, 24 Aug 2025 17:47:51 +0000
From: &quot;Your Shop Name&quot; &lt;johir@pixelbuildbd.com&gt;
Return-Path: &lt;johir@pixelbuildbd.com&gt;
To: johirulislam6442@gmail.com
Subject: =?UTF-8?Q?New=20Order=20Received?=
Reply-To: &lt;johir@pixelbuildbd.com&gt;
User-Agent: CodeIgniter
X-Sender: johir@pixelbuildbd.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;68ab5047943445.73334085@pixelbuildbd.com&gt;
Mime-Version: 1.0

</pre>')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 17:54:14 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-08-24 17:54:14 --> 220 smtp.gmail.com ESMTP 41be03b00d2f7-b49cbb7b375sm4671100a12.29 - gsmtp

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

starttls: 220 2.0.0 Ready to start TLS

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 41be03b00d2f7-b49cbb7b375sm4671100a12.29 - gsmtp

CRITICAL - 2025-08-24 17:54:14 --> TypeError: implode(): Argument #2 ($array) must be of type ?array, string given
[Method: POST, Route: order/submit]
in APPPATH\Controllers\ShopController.php on line 110.
 1 APPPATH\Controllers\ShopController.php(110): implode(', ', '220 smtp.gmail.com ESMTP 41be03b00d2f7-b49cbb7b375sm4671100a12.29 - gsmtp
<br><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre><pre>starttls: 220 2.0.0 Ready to start TLS
</pre><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre>Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 41be03b00d2f7-b49cbb7b375sm4671100a12.29 - gsmtp
<br>Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br><pre>Date: Sun, 24 Aug 2025 17:54:09 +0000
From: &quot;Your Shop Name&quot; &lt;johirulislam2966@gmail.com&gt;
Return-Path: &lt;johirulislam2966@gmail.com&gt;
To: johirulislam6442@gmail.com
Subject: =?UTF-8?Q?New=20Order=20Received?=
Reply-To: &lt;johirulislam2966@gmail.com&gt;
User-Agent: CodeIgniter
X-Sender: johirulislam2966@gmail.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;68ab51c132bb99.02706273@gmail.com&gt;
Mime-Version: 1.0

</pre>')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 17:54:25 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-08-24 17:54:25 --> 220 smtp.gmail.com ESMTP d9443c01a7336-24668880a99sm47040735ad.121 - gsmtp

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

starttls: 220 2.0.0 Ready to start TLS

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-24668880a99sm47040735ad.121 - gsmtp

CRITICAL - 2025-08-24 17:54:25 --> TypeError: implode(): Argument #2 ($array) must be of type ?array, string given
[Method: POST, Route: order/submit]
in APPPATH\Controllers\ShopController.php on line 110.
 1 APPPATH\Controllers\ShopController.php(110): implode(', ', '220 smtp.gmail.com ESMTP d9443c01a7336-24668880a99sm47040735ad.121 - gsmtp
<br><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre><pre>starttls: 220 2.0.0 Ready to start TLS
</pre><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre>Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-24668880a99sm47040735ad.121 - gsmtp
<br>Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br><pre>Date: Sun, 24 Aug 2025 17:54:21 +0000
From: &quot;Your Shop Name&quot; &lt;johirulislam2966@gmail.com&gt;
Return-Path: &lt;johirulislam2966@gmail.com&gt;
To: johirulislam6442@gmail.com
Subject: =?UTF-8?Q?New=20Order=20Received?=
Reply-To: &lt;johirulislam2966@gmail.com&gt;
User-Agent: CodeIgniter
X-Sender: johirulislam2966@gmail.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;68ab51cd01a2b1.55953361@gmail.com&gt;
Mime-Version: 1.0

</pre>')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 18:04:20 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-08-24 18:04:20 --> 220 smtp.gmail.com ESMTP d2e1a72fcca58-7704821293asm4155448b3a.15 - gsmtp

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

starttls: 220 2.0.0 Ready to start TLS

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials d2e1a72fcca58-7704821293asm4155448b3a.15 - gsmtp

CRITICAL - 2025-08-24 18:04:20 --> TypeError: implode(): Argument #2 ($array) must be of type ?array, string given
[Method: POST, Route: order/submit]
in APPPATH\Controllers\ShopController.php on line 110.
 1 APPPATH\Controllers\ShopController.php(110): implode(', ', '220 smtp.gmail.com ESMTP d2e1a72fcca58-7704821293asm4155448b3a.15 - gsmtp
<br><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre><pre>starttls: 220 2.0.0 Ready to start TLS
</pre><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre>Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials d2e1a72fcca58-7704821293asm4155448b3a.15 - gsmtp
<br>Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br><pre>Date: Sun, 24 Aug 2025 18:04:15 +0000
From: &quot;Your Shop Name&quot; &lt;johirulislam2966@gmail.com&gt;
Return-Path: &lt;johirulislam2966@gmail.com&gt;
To: johirulislam6442@gmail.com
Subject: =?UTF-8?Q?New=20Order=20Received?=
Reply-To: &lt;johirulislam2966@gmail.com&gt;
User-Agent: CodeIgniter
X-Sender: johirulislam2966@gmail.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;68ab541f93b7a8.21723015@gmail.com&gt;
Mime-Version: 1.0

</pre>')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 18:13:43 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-08-24 18:13:43 --> 220 smtp.gmail.com ESMTP d2e1a72fcca58-77059928c5asm1759159b3a.1 - gsmtp

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

starttls: 220 2.0.0 Ready to start TLS

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials d2e1a72fcca58-77059928c5asm1759159b3a.1 - gsmtp

CRITICAL - 2025-08-24 18:13:43 --> TypeError: implode(): Argument #2 ($array) must be of type ?array, string given
[Method: POST, Route: order/submit]
in APPPATH\Controllers\ShopController.php on line 110.
 1 APPPATH\Controllers\ShopController.php(110): implode(', ', '220 smtp.gmail.com ESMTP d2e1a72fcca58-77059928c5asm1759159b3a.1 - gsmtp
<br><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre><pre>starttls: 220 2.0.0 Ready to start TLS
</pre><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre>Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials d2e1a72fcca58-77059928c5asm1759159b3a.1 - gsmtp
<br>Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br><pre>Date: Sun, 24 Aug 2025 18:13:39 +0000
From: &quot;Your Shop Name&quot; &lt;johirulislam2966@gmail.com&gt;
Return-Path: &lt;johirulislam2966@gmail.com&gt;
To: johirulislam6442@gmail.com
Subject: =?UTF-8?Q?New=20Order=20Received?=
Reply-To: &lt;johirulislam2966@gmail.com&gt;
User-Agent: CodeIgniter
X-Sender: johirulislam2966@gmail.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;68ab5653737a43.69991335@gmail.com&gt;
Mime-Version: 1.0

</pre>')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 18:15:32 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-08-24 18:15:32 --> 220 smtp.gmail.com ESMTP 41be03b00d2f7-b49cbbbaffdsm4697960a12.51 - gsmtp

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

starttls: 220 2.0.0 Ready to start TLS

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 41be03b00d2f7-b49cbbbaffdsm4697960a12.51 - gsmtp

CRITICAL - 2025-08-24 18:15:32 --> TypeError: implode(): Argument #2 ($array) must be of type ?array, string given
[Method: POST, Route: order/submit]
in APPPATH\Controllers\ShopController.php on line 110.
 1 APPPATH\Controllers\ShopController.php(110): implode(', ', '220 smtp.gmail.com ESMTP 41be03b00d2f7-b49cbbbaffdsm4697960a12.51 - gsmtp
<br><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre><pre>starttls: 220 2.0.0 Ready to start TLS
</pre><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre>Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 41be03b00d2f7-b49cbbbaffdsm4697960a12.51 - gsmtp
<br>Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br><pre>Date: Sun, 24 Aug 2025 18:15:27 +0000
From: &quot;Your Shop Name&quot; &lt;johirulislam2966@gmail.com&gt;
Return-Path: &lt;johirulislam2966@gmail.com&gt;
To: johirulislam6442@gmail.com
Subject: =?UTF-8?Q?New=20Order=20Received?=
Reply-To: &lt;johirulislam2966@gmail.com&gt;
User-Agent: CodeIgniter
X-Sender: johirulislam2966@gmail.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;68ab56bf823788.37882681@gmail.com&gt;
Mime-Version: 1.0

</pre>')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 18:22:56 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-08-24 18:22:56 --> 220 smtp.gmail.com ESMTP d9443c01a7336-2466877a06esm47940055ad.31 - gsmtp

hello: 250-smtp.gmail.com at your service, [182.252.75.79]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

starttls: 220 2.0.0 Ready to start TLS

hello: 250-smtp.gmail.com at your service, [182.252.75.79]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-2466877a06esm47940055ad.31 - gsmtp

CRITICAL - 2025-08-24 18:22:56 --> TypeError: implode(): Argument #2 ($array) must be of type ?array, string given
[Method: POST, Route: order/submit]
in APPPATH\Controllers\ShopController.php on line 110.
 1 APPPATH\Controllers\ShopController.php(110): implode(', ', '220 smtp.gmail.com ESMTP d9443c01a7336-2466877a06esm47940055ad.31 - gsmtp
<br><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.79]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre><pre>starttls: 220 2.0.0 Ready to start TLS
</pre><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.79]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre>Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-2466877a06esm47940055ad.31 - gsmtp
<br>Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br><pre>Date: Sun, 24 Aug 2025 18:22:52 +0000
From: &quot;Your Shop Name&quot; &lt;johirulislam2966@gmail.com&gt;
Return-Path: &lt;johirulislam2966@gmail.com&gt;
To: johirulislam6442@gmail.com
Subject: =?UTF-8?Q?New=20Order=20Received?=
Reply-To: &lt;johirulislam2966@gmail.com&gt;
User-Agent: CodeIgniter
X-Sender: johirulislam2966@gmail.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;68ab587c9b3bb5.32613522@gmail.com&gt;
Mime-Version: 1.0

</pre>')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 18:25:41 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-08-24 18:25:41 --> 220 smtp.gmail.com ESMTP 98e67ed59e1d1-324f80d4de6sm5554781a91.2 - gsmtp

hello: 250-smtp.gmail.com at your service, [182.252.75.79]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

starttls: 220 2.0.0 Ready to start TLS

hello: 250-smtp.gmail.com at your service, [182.252.75.79]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 98e67ed59e1d1-324f80d4de6sm5554781a91.2 - gsmtp

CRITICAL - 2025-08-24 18:25:41 --> TypeError: implode(): Argument #2 ($array) must be of type ?array, string given
[Method: POST, Route: order/submit]
in APPPATH\Controllers\ShopController.php on line 110.
 1 APPPATH\Controllers\ShopController.php(110): implode(', ', '220 smtp.gmail.com ESMTP 98e67ed59e1d1-324f80d4de6sm5554781a91.2 - gsmtp
<br><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.79]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre><pre>starttls: 220 2.0.0 Ready to start TLS
</pre><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.79]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre>Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 98e67ed59e1d1-324f80d4de6sm5554781a91.2 - gsmtp
<br>Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br><pre>Date: Sun, 24 Aug 2025 18:25:37 +0000
From: &quot;Your Shop Name&quot; &lt;johirulislam2966@gmail.com&gt;
Return-Path: &lt;johirulislam2966@gmail.com&gt;
To: johirulislam6442@gmail.com
Subject: =?UTF-8?Q?New=20Order=20Received?=
Reply-To: &lt;johirulislam2966@gmail.com&gt;
User-Agent: CodeIgniter
X-Sender: johirulislam2966@gmail.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;68ab592116b954.28355807@gmail.com&gt;
Mime-Version: 1.0

</pre>')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 18:25:53 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-08-24 18:25:53 --> 220 smtp.gmail.com ESMTP 98e67ed59e1d1-3254ae8a9efsm4854892a91.9 - gsmtp

hello: 250-smtp.gmail.com at your service, [182.252.75.79]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

starttls: 220 2.0.0 Ready to start TLS

hello: 250-smtp.gmail.com at your service, [182.252.75.79]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 98e67ed59e1d1-3254ae8a9efsm4854892a91.9 - gsmtp

CRITICAL - 2025-08-24 18:25:53 --> TypeError: implode(): Argument #2 ($array) must be of type ?array, string given
[Method: POST, Route: order/submit]
in APPPATH\Controllers\ShopController.php on line 110.
 1 APPPATH\Controllers\ShopController.php(110): implode(', ', '220 smtp.gmail.com ESMTP 98e67ed59e1d1-3254ae8a9efsm4854892a91.9 - gsmtp
<br><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.79]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre><pre>starttls: 220 2.0.0 Ready to start TLS
</pre><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.79]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre>Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 98e67ed59e1d1-3254ae8a9efsm4854892a91.9 - gsmtp
<br>Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br><pre>Date: Sun, 24 Aug 2025 18:25:48 +0000
From: &quot;Your Shop Name&quot; &lt;johirulislam2966@gmail.com&gt;
Return-Path: &lt;johirulislam2966@gmail.com&gt;
To: johirulislam6442@gmail.com
Subject: =?UTF-8?Q?New=20Order=20Received?=
Reply-To: &lt;johirulislam2966@gmail.com&gt;
User-Agent: CodeIgniter
X-Sender: johirulislam2966@gmail.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;68ab592c86d545.80449335@gmail.com&gt;
Mime-Version: 1.0

</pre>')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 18:29:00 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2025-08-24 18:29:00 --> 220 smtp.gmail.com ESMTP 98e67ed59e1d1-3254b809c9asm4857989a91.26 - gsmtp

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

starttls: 220 2.0.0 Ready to start TLS

hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8

Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 98e67ed59e1d1-3254b809c9asm4857989a91.26 - gsmtp

CRITICAL - 2025-08-24 18:29:00 --> TypeError: implode(): Argument #2 ($array) must be of type ?array, string given
[Method: POST, Route: order/submit]
in APPPATH\Controllers\ShopController.php on line 110.
 1 APPPATH\Controllers\ShopController.php(110): implode(', ', '220 smtp.gmail.com ESMTP 98e67ed59e1d1-3254b809c9asm4857989a91.26 - gsmtp
<br><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre><pre>starttls: 220 2.0.0 Ready to start TLS
</pre><pre>hello: 250-smtp.gmail.com at your service, [182.252.75.78]
250-SIZE 35882577
250-8BITMIME
250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-CHUNKING
250 SMTPUTF8
</pre>Failed to authenticate password. Error: 535-5.7.8 Username and Password not accepted. For more information, go to
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 98e67ed59e1d1-3254b809c9asm4857989a91.26 - gsmtp
<br>Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br><pre>Date: Sun, 24 Aug 2025 18:28:55 +0000
From: &quot;Your Shop Name&quot; &lt;johirulislam2966@gmail.com&gt;
Return-Path: &lt;johirulislam2966@gmail.com&gt;
To: johirulislam6442@gmail.com
Subject: =?UTF-8?Q?New=20Order=20Received?=
Reply-To: &lt;johirulislam2966@gmail.com&gt;
User-Agent: CodeIgniter
X-Sender: johirulislam2966@gmail.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;68ab59e70602a7.86154444@gmail.com&gt;
Mime-Version: 1.0

</pre>')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
