ERROR - 2025-08-24 03:13:59 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 03:13:59 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:13:59 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:13:59\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:13:59\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:13:59 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:13:59\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:13:59\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:13:59\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 03:14:04 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 03:14:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:04\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:04\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:04 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 03:14:09 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 03:14:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:09 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:09 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 03:14:09 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 03:14:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:09 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:09 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:09\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 03:14:10 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 03:14:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:10 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:10\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:10\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 03:14:10 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:10\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:10\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'6865465465465\', 0, \'2025-08-24 03:14:10\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 04:01:34 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 04:01:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:01:34 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:34\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:34\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:01:34 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:34\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:34\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:34\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 04:01:42 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 04:01:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:01:42 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:42\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:42\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:01:42 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:42\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:42\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:01:42\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 04:02:18 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 04:02:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:02:18 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:02:18\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:02:18\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:02:18 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:02:18\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:02:18\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:02:18\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 04:05:28 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 04:05:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:05:28 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:05:28\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:05:28\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 04:05:28 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:05:28\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:05:28\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'fgf\', 0, \'2025-08-24 04:05:28\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 07:37:47 --> mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#6 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#7 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2025-08-24 07:37:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 2 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 07:37:48 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'yuyuyu\', 0, \'2025-08-24 07:37:47\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'yuyuyu\', 0, \'2025-08-24 07:37:47\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 4 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
11 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 07:37:48 --> [Caused by] mysqli_sql_exception: Unknown column 'customer_mobile' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'yuyuyu\', 0, \'2025-08-24 07:37:47\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'yuyuyu\', 0, \'2025-08-24 07:37:47\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (\'joh\', \'65656565\', \'yuyuyu\', 0, \'2025-08-24 07:37:47\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `total_price`, `created_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :total_price:, :created_at:)', [...], false)
 5 APPPATH\Controllers\ShopController.php(63): CodeIgniter\Database\BaseBuilder->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:17:47 --> ErrorException: Class App\Database\Migrations\CreateBooks contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (CodeIgniter\Database\Migration::down)
[Method: CLI, Route: migrate]
in APPPATH\Database\Migrations\2025-08-23-184439_CreateBooks.php on line 7.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2025-08-24 08:18:00 --> ErrorException: Class App\Database\Migrations\CreateBooks contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (CodeIgniter\Database\Migration::down)
[Method: CLI, Route: migrate]
in APPPATH\Database\Migrations\2025-08-23-184439_CreateBooks.php on line 7.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2025-08-24 08:21:33 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:21:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:21:33 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:21:33\', \'2025-08-24 08:21:33\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:21:33\', \'2025-08-24 08:21:33\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:21:33 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:21:33\', \'2025-08-24 08:21:33\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:21:33\', \'2025-08-24 08:21:33\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:21:33\', \'2025-08-24 08:21:33\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 08:23:37 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:23:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:23:37 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:37\', \'2025-08-24 08:23:37\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:37\', \'2025-08-24 08:23:37\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:23:37 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:37\', \'2025-08-24 08:23:37\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:37\', \'2025-08-24 08:23:37\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:37\', \'2025-08-24 08:23:37\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 08:23:47 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:23:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:23:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:46\', \'2025-08-24 08:23:46\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:46\', \'2025-08-24 08:23:46\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:23:47 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:46\', \'2025-08-24 08:23:46\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:46\', \'2025-08-24 08:23:46\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:23:46\', \'2025-08-24 08:23:46\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 08:29:54 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:29:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:29:54 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:29:54\', \'2025-08-24 08:29:54\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:29:54\', \'2025-08-24 08:29:54\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:29:54 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:29:54\', \'2025-08-24 08:29:54\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:29:54\', \'2025-08-24 08:29:54\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'dfdfdf\', \'2025-08-24 08:29:54\', \'2025-08-24 08:29:54\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 08:30:03 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:30:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:30:03 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:03\', \'2025-08-24 08:30:03\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:03\', \'2025-08-24 08:30:03\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:30:03 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:03\', \'2025-08-24 08:30:03\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:03\', \'2025-08-24 08:30:03\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:03\', \'2025-08-24 08:30:03\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 08:30:14 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:30:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:30:14 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:14\', \'2025-08-24 08:30:14\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:14\', \'2025-08-24 08:30:14\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:30:14 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:14\', \'2025-08-24 08:30:14\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:14\', \'2025-08-24 08:30:14\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:14\', \'2025-08-24 08:30:14\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 08:30:48 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:30:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:30:48 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:48\', \'2025-08-24 08:30:48\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:48\', \'2025-08-24 08:30:48\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:30:48 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:48\', \'2025-08-24 08:30:48\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:48\', \'2025-08-24 08:30:48\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:30:48\', \'2025-08-24 08:30:48\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
ERROR - 2025-08-24 08:32:34 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\codeigniter4order\system\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `or...', 0)
#1 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `or...')
#2 C:\xampp\htdocs\codeigniter4order\system\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `or...')
#3 C:\xampp\htdocs\codeigniter4order\system\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `or...', Array, false)
#4 C:\xampp\htdocs\codeigniter4order\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\codeigniter4order\system\BaseModel.php(838): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\codeigniter4order\system\Model.php(797): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\codeigniter4order\app\Controllers\ShopController.php(37): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(933): App\Controllers\ShopController->submit()
#9 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
#10 C:\xampp\htdocs\codeigniter4order\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\codeigniter4order\system\Boot.php(363): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\codeigniter4order\system\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\codeigniter4order\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp\htdocs\codeigniter4order\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2025-08-24 08:32:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
[Method: POST, Route: order/submit]
in SYSTEMPATH\Database\BaseConnection.php on line 684.
 1 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:32:34 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 332.
 1 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:32:34\', \'2025-08-24 08:32:34\')')
 2 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:32:34\', \'2025-08-24 08:32:34\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
 9 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
10 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 08:32:34 --> [Caused by] mysqli_sql_exception: Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 327.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(327): mysqli->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:32:34\', \'2025-08-24 08:32:34\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(729): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:32:34\', \'2025-08-24 08:32:34\')')
 3 SYSTEMPATH\Database\BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (\'joh\', \'65656565\', \'kjk\', \'2025-08-24 08:32:34\', \'2025-08-24 08:32:34\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2345): CodeIgniter\Database\BaseConnection->query('INSERT INTO `orders` (`customer_name`, `customer_mobile`, `customer_address`, `created_at`, `updated_at`) VALUES (:customer_name:, :customer_mobile:, :customer_address:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(838): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(797): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\ShopController.php(37): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\ShopController->submit()
10 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ShopController))
11 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
CRITICAL - 2025-08-24 12:33:38 --> ErrorException: Undefined array key "title"
[Method: GET, Route: admin/books]
in APPPATH\Views\admin\books.php on line 11.
 1 APPPATH\Views\admin\books.php(11): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "title"', 'C:\\xampp\\htdocs\\codeigniter4order\\app\\Views\\admin\\books.php', 11)
 2 SYSTEMPATH\View\View.php(226): include('C:\\xampp\\htdocs\\codeigniter4order\\app\\Views\\admin\\books.php')
 3 SYSTEMPATH\View\View.php(229): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1167): CodeIgniter\View\View->render('admin/books', [], true)
 5 APPPATH\Controllers\Admin\Books.php(15): view('admin/books', [...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Admin\Books->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Books))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(363): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(68): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\codeigniter4order\\public\\index.php')
